### ISSUE TITLE
[1.14.4] No dust from Iron or Gold

### ISSUE THREAD

**Issue by FuuNoKamiOka** [TheOnePath/Better-Flint-And-Steels#1]
I don't know why it is, but I can not get Iron or Gold dust to be a thing. There is no recipe or smelting recipe for the dusts.

Forge version: 28.1.104
Mod Version: 1.14.4-1.2.4

**Comment by TheOnePath** [comment]
Hi FuuNoKamiOka,

Apologies for the prolonged response due to studies. I'm working on making sure that this isn't an issue, BFS will use the More Ores mod I'm working on to craft the relavent items. Please bare with me until the redevelopment of that mod has been released.
