### ISSUE TITLE
[Suggestion] More additions

### ISSUE THREAD

**Issue by FuuNoKamiOka** [TheOnePath/Better-Flint-And-Steels#2]
I think it would benefit you and the mod if you added more to it. Maybe something simple like blocks of the ores for example. If you'd want to expand into more things I think weapons/tools and armor would be great. This is one of the few mods that have ore doubling and I think if you took advantage of that and added more you'd see more people using it.

**Comment by TheOnePath** [comment]
Hi FuuNoKamiOka,

I believe I have answered this question with your issue raised over at [More Ores](https://github.com/TheOnePath/More-Ores/issues/1).

Thank you.
